### ISSUE TITLE
Can you put double quotes around the host string?

### ISSUE THREAD

**Issue by andylockran** [jaw187/node-traceroute#4]
I think this would make the output a valid json object.
Would be nice to also include attributes for hostname and client IP.

**Comment by jaw187** [comment]
This project is due an update.  I'll include this in an update.

**Comment by jaw187** [comment]
@andylockran I just sat down to close out this issue, but I'm not really sure what you're asking for in regards to double quotes and the host string.

**Comment by andylockran** [comment]
Hey James,

It'd just be a case of passing the output through a json validator to make
sure it's valid json.

Regards,

Andy

**Comment by andylockran** [comment]
@jaw187 did that make sense?
